language: scala
scala:
- 2.12.8
- 2.13.0
script:
- sbt clean coverage test coverageReport
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: sWogP/oekr24s3cOm9HQweBI0hzzR0jnX/ZK3NqEDKCoCtyEPW1efR7xwbGIRVSkCwYch61QUKJmcPKWYMqaNq55Y5GYKH9b4ztI0EIs+mN92yAPUhqj0DTc8EK9Syjdmh/urE/j0LgbxwKNiJB+VkgwTaQZPrtAHeBxiqOE1228HQGbgXlMjfjsuNcmz4EDfjoV67lvkfhVuaKgVs5zbXb5XgiaXYsyXxo/bjjdTiP6vXsmdKWY+cbMffHkZ8JTesesDcMLtDc4Jf8DVBwmoLhiQBiQchBzDX65+PBoWwKnlpslnIZgSvfRvDHH7CVwWCuYVYwtHCWBmWw0LpUhbOJoCJISJBV269M7L8m/mV5m/T+YOXZ1n1J9cLLOPAT2sf0dvOE5Ca8+kQnN9KLE6F5baKj5TXWOZ9uRQdYaU9BlJ37G4z91nw8IzF0CtBYT82KM9ios0k4LU89c5H6hnnXczRAZ1lhLvLTKfEcNIUEBLwtp3DFff4gzNbQ3UCXkVSWzK4vd4WdG8cnhUWDX6R5LqTFwZyevbzBpRgocDfeHtB7ug8dRuBsHe149dDCQccU28sa2Qz1muc0wkCMG8AnYuflHfhPjZ7VUiE5Z20bScixiJEM5Dy1FCfrpqFk8ExbrogdOK86IWwKJ682f18i5EMa2/5cB3pgfWRyp0wU=
  - secure: k5+qyP5ehQMFEfnGmeLfrSG4+3jn/CfmC3HnIw6hcWOxH12eNajQGVbzpziqy5EoXXb2Nl428KmCiy6/2e6O21XGvLWk4YXTtUXLVcHcn3dNT1Q+dU6NAlajNvoPaPbJn2i+a0DkmebjVetytncjpPz3YCaP13L8/ezN5p7bWXUy/sVyHuvpK6/qFCUsCruzQa82UMqYKzFqIQBgFpWDKF+qb1283E870BlqSF8jVHwbyBUhX+BMq8LTDL1vjcZdBrqTR4rDnjboVND+HzCZ5dsZ0rm+lh/7DWbRPLoXTxSlVv5gc28OvFVinfEVbf2jiPZCX92gaQwU07QYHLsxQVuKw3ylcfoRHaixktuAiOlvF/aj4C7SCKfZJadw7xBTIW+2pVeBt7XNuW6PLXAlljxfAfh8aFZcRHAEKMD17F402LVcFiCp/0evbmKvwJjA6mxVmcnSRG0J18QgC21x4byunSnmTO2qG4o3rEmBIPpRnWsSjARYGx0PxbA9Inducd1HK10gTtpgmU9MRG/mFiPkKMhEtdriKjwZNJtemnfQ4J/0tp67WYN1wBT5JXRVdaMbgLewpoJiA9mHEphQVbUzZr8xkvE6jQpdBwgN1YBxjuMbkha4B3wvtDU+q38rymN6ToP4C/yCJl/CVoGbqWMlps8U1bZeSPT499iM4iQ=
before_install:
- openssl aes-256-cbc -K $encrypted_25a884814f46_key -iv $encrypted_25a884814f46_iv
  -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d
